project:
  type: website
  output-dir: docs

execute:
  echo: false      # Do not show the source code in the output
  warning: false   # Do not show warning messages
  message: false   # Do not show package loading messages

website:
  title: "UBCBG Climate Analysis"
  navbar:
    background: "#002145"
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/2025_taxonomy_backbone_EDA.ipynb
        text: "Taxonomy Backbone"
      - href: notebooks/data_validation.ipynb
        text: "Data Validation"
      - href: notebooks/Joined_EDA.ipynb
        text: "Exploratory Analysis"
      - href: maps.qmd
        text: "Suitability Ratings Map"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



