project:
  type: website
  output-dir: docs

execute:
  echo: false      # Do not show the source code in the output
  warning: false   # Do not show warning messages
  message: false   # Do not show package loading messages

website:
  title: "UBCBG: Climate Assessment Tool (CAT) Analysis"
  navbar:
    background: "#002145"
    left:
      - href: index.qmd
        text: Home
      - href: methods.qmd
        text: "Data Sources & Methods"
      - href: notebooks/2025_taxonomy_backbone_EDA.ipynb
        text: "Global Taxonomy Backbone"
      - href: notebooks/data_validation.ipynb
        text: "CAT v1 vs. v2 : Data validation"
      - href: notebooks/Joined_EDA.ipynb
        text: "Exploratory Analysis of the UBC CAT data"
      - href: maps.qmd
        text: "Era based Suitability Ratings Map"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



